server:
  port: 8083


spring:
  application:
    name: RATING-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/rating-service
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true